//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using Elements.Serialization.JSON;
using Elements.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements.Geometry
{
#pragma warning disable // Disable all warnings

    /// <summary>The base class for all geometry</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [JsonInheritanceAttribute("Mesh", typeof(Mesh))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    [UserElement]
    public partial class Geometry : Element
    {
        [Newtonsoft.Json.JsonConstructor]
        public Geometry(Material @material, System.Guid @id, string @name)
            : base(id, name)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Geometry>
            ();
            if (validator != null)
            {
                validator.PreConstruct(new object[] { @material, @id, @name });
            }

            this.Material = @material;

            if (validator != null)
            {
                validator.PostConstruct(this);
            }
        }

        /// <summary>The material for this piece of geometry.</summary>
        [Newtonsoft.Json.JsonProperty("Material", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Material Material { get; set; }


    }
}