namespace Elements
{
    /// <summary>
    /// The source of snapping points.
    /// </summary>
    public enum SnappingPointsSource
    {
        /// <summary>
        /// Element doesn't have snapping points.
        /// </summary>
        None,
        /// <summary>
        /// The ElementRepresentation.
        /// </summary>
        ElementRepresentation,
        /// <summary>
        /// Automatically generate snapping points based on the element's edges.
        /// </summary>
        AutoGenerated
    }
}