using Elements.Geometry;
using Elements.Geometry.Solids;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.24.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>A transform.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Transform : Component
    {
        /// <summary>The origin.</summary>
        [Newtonsoft.Json.JsonProperty("Origin", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 Origin { get; set; }
    
        /// <summary>The X axis.</summary>
        [Newtonsoft.Json.JsonProperty("XAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 XAxis { get; set; }
    
        /// <summary>The Y axis.</summary>
        [Newtonsoft.Json.JsonProperty("YAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 YAxis { get; set; }
    
        /// <summary>The Z axis.</summary>
        [Newtonsoft.Json.JsonProperty("ZAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 ZAxis { get; set; }
    
    
    }
}