//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v11.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using Elements.Validators;
using Elements.Serialization.JSON;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements.Properties
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v11.0.0.0)")]
    public enum NumericPropertyUnitType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Length")]
        Length = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Mass")]
        Mass = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Force")]
        Force = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Area")]
        Area = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pressure")]
        Pressure = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Currency")]
        Currency = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Time")]
        Time = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Number")]
        Number = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Volume")]
        Volume = 8,
    
    }
}