//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.24.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Elements.Properties
{
    #pragma warning disable // Disable all warnings

    using Elements.ElementTypes;
    using Elements.GeoJSON;
    using Elements.Geometry;
    using Elements.Geometry.Solids;
    using Elements.Properties;
    using Elements.Serialization.JSON;
    using System;
    using System.Collections.Generic;
    
    /// <summary>A property with a numeric value.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class NumericProperty : Property
    {
        /// <summary>The property's value</summary>
        [Newtonsoft.Json.JsonProperty("Value", Required = Newtonsoft.Json.Required.Always)]
        public  double Value { get; internal set; }
    
        /// <summary>The value type.</summary>
        [Newtonsoft.Json.JsonProperty("ValueType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public  NumericPropertyValueType ValueType { get; internal set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
    
        public static NumericProperty FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<NumericProperty>(data);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum NumericPropertyValueType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Length")]
        Length = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Mass")]
        Mass = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Force")]
        Force = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Area")]
        Area = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pressure")]
        Pressure = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Currency")]
        Currency = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Time")]
        Time = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Number")]
        Number = 7,
    
    }
}