//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.24.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Elements.Properties
{
    #pragma warning disable // Disable all warnings

    using Elements.GeoJSON;
    using Elements.Geometry;
    using Elements.Geometry.Solids;
    using Elements.Properties;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>A property with a numeric value.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class NumericProperty 
    {
        /// <summary>The property's value</summary>
        [Newtonsoft.Json.JsonProperty("Value", Required = Newtonsoft.Json.Required.Always)]
        public  double Value { get; internal set; }
    
        /// <summary>The unit type.</summary>
        [Newtonsoft.Json.JsonProperty("UnitType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public  NumericPropertyUnitType UnitType { get; internal set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum NumericPropertyUnitType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Length")]
        Length = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Mass")]
        Mass = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Force")]
        Force = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Area")]
        Area = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Pressure")]
        Pressure = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Currency")]
        Currency = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Time")]
        Time = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Number")]
        Number = 7,
    
    }
}