//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.24.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Elements.Properties
{
    #pragma warning disable // Disable all warnings

    using Elements.Geometry;
    using Elements.Geometry.Solids;
    using Elements.Properties;
    using System.Collections.Generic;
    
    /// <summary>A set of properties.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class PropertySet 
    {
        [Newtonsoft.Json.JsonProperty("Properties", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.IList<Property> Properties { get; internal set; } = new System.Collections.Generic.List<Property>();
    
    
    }
}