//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.4.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using Elements.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements.Geometry
{
    #pragma warning disable // Disable all warnings

    /// <summary>An arc defined by a CCW rotation around a center between a start angle and an end angle.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.4.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Arc : Curve
    {
        [Newtonsoft.Json.JsonConstructor]
        public Arc(Vector3 @center, double @radius, double @startAngle, double @endAngle)
            : base()
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Arc>();
            if(validator != null)
            {
                validator.Validate(new object[]{ @center, @radius, @startAngle, @endAngle});
            }
        
            this.Center = @center;
            this.Radius = @radius;
            this.StartAngle = @startAngle;
            this.EndAngle = @endAngle;
        }
    
        /// <summary>The center of the arc.</summary>
        [Newtonsoft.Json.JsonProperty("Center", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 Center { get; set; }
    
        /// <summary>The radius of the arc.</summary>
        [Newtonsoft.Json.JsonProperty("Radius", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, double.MaxValue)]
        public double Radius { get; set; }
    
        /// <summary>The angle from 0.0, in degrees, at which the arc will start with respect to the positive X axis.</summary>
        [Newtonsoft.Json.JsonProperty("StartAngle", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, 360.0D)]
        public double StartAngle { get; set; }
    
        /// <summary>The angle from 0.0, in degrees, at which the arc will end with respect to the positive X axis.</summary>
        [Newtonsoft.Json.JsonProperty("EndAngle", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(0.0D, 360.0D)]
        public double EndAngle { get; set; }
    
    
    }
}