using Elements.Geometry;
using Elements.Geometry.Solids;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.24.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Elements.Geometry
{
    #pragma warning disable // Disable all warnings

    /// <summary>An RGBA color.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.24.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Color 
    {
        /// <summary>The red component of the color between 0.0 and 1.0.</summary>
        [Newtonsoft.Json.JsonProperty("Red", Required = Newtonsoft.Json.Required.Always)]
        public double Red { get; set; }
    
        /// <summary>The green component of the color between 0.0 and 1.0..</summary>
        [Newtonsoft.Json.JsonProperty("Green", Required = Newtonsoft.Json.Required.Always)]
        public double Green { get; set; }
    
        /// <summary>The blue component of the color between 0.0 and 1.0..</summary>
        [Newtonsoft.Json.JsonProperty("Blue", Required = Newtonsoft.Json.Required.Always)]
        public double Blue { get; set; }
    
        /// <summary>The alpha component of the color between 0.0 and 1.0..</summary>
        [Newtonsoft.Json.JsonProperty("Alpha", Required = Newtonsoft.Json.Required.Always)]
        public double Alpha { get; set; }
    
    
    }
}