//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.27.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Elements.Geometry
{
    #pragma warning disable // Disable all warnings

    /// <summary>A right-handed coordinate system with +Z up.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.27.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Transform 
    {
        /// <summary>The origin.</summary>
        [Newtonsoft.Json.JsonProperty("Origin", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 Origin { get;  set; }
    
        /// <summary>The X axis.</summary>
        [Newtonsoft.Json.JsonProperty("XAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 XAxis { get;  set; }
    
        /// <summary>The Y axis.</summary>
        [Newtonsoft.Json.JsonProperty("YAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 YAxis { get;  set; }
    
        /// <summary>The Z axis.</summary>
        [Newtonsoft.Json.JsonProperty("ZAxis", Required = Newtonsoft.Json.Required.AllowNull)]
        public Vector3 ZAxis { get;  set; }
    
    
    }
}